ALLERGEN_SEEDS: list[tuple[str, str, int]] = [
    ("EGGS", "난류", 1),
    ("MILK", "우유", 2),
    ("BUCKWHEAT", "메밀", 3),
    ("PEANUT", "땅콩", 4),
    ("SOYBEAN", "대두", 5),
    ("WHEAT", "밀", 6),
    ("MACKEREL", "고등어", 7),
    ("CRAB", "게", 8),
    ("SHRIMP", "새우", 9),
    ("PORK", "돼지고기", 10),
    ("PEACH", "복숭아", 11),
    ("TOMATO", "토마토", 12),
    ("SULFITES", "아황산류", 13),
    ("WALNUT", "호두", 14),
    ("CHICKEN", "닭고기", 15),
    ("BEEF", "쇠고기", 16),
    ("SQUID", "오징어", 17),
    ("SHELLFISH", "조개류", 18),
    ("PINE_NUT", "잣", 19),
]
